.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge-member-functions - Debug ]----------"
	@cd "Challenge" && "$(MAKE)" -f  "Challenge-member-functions.mk"
clean:
	@echo "----------Cleaning project:[ Challenge-member-functions - Debug ]----------"
	@cd "Challenge" && "$(MAKE)" -f  "Challenge-member-functions.mk" clean
